-- Outpost Postgres schema, v0.1 (2026-09-18). Companion to README.md and TENANT-ISOLATION.md.
--
-- Layout
--   platform.*  tenants, users, sessions, engagements. No tenant data, no RLS. Owned by
--               outpost_migrate; the request-path role gets narrow grants.
--   catalog.*   shared, read-only reference data: connector types, missions, playbooks,
--               agents, MCP allowlist. No tenant_id by design.
--   outpost.*   every tenant-scoped table. tenant_id NOT NULL on all of them, defaulting to
--               the request's acting tenant, with RLS ENABLED and FORCED and a
--               tenant_isolation policy. check_rls.sql fails CI if any table here breaks that.
--
-- Roles
--   outpost_migrate      owns everything, runs this file and migrations. Never used by the app.
--   outpost_app          request path. NOBYPASSRLS. DML on outpost.*, INSERT-only on audit.
--   outpost_provisioner  tenant creation and offboarding job. Writes platform.tenants.
--
-- Conventions
--   Ids are UUIDv7 generated by the application (time-ordered, no sequence to leak counts);
--   gen_random_uuid() is the fallback default so raw SQL in tests still works.
--   Enumerations are text + CHECK so a new value is a migration, not a type rebuild.
--   Child tables reference parents by (tenant_id, id) so a row can never point across tenants.
--
-- Run: psql -v ON_ERROR_STOP=1 -f schema.sql   (as a superuser the first time, for the roles)

\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- 0. Roles (superuser section). Idempotent.
-- ---------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'outpost_migrate') then
    create role outpost_migrate login;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'outpost_app') then
    create role outpost_app login nobypassrls;
  end if;
  if not exists (select 1 from pg_roles where rolname = 'outpost_provisioner') then
    create role outpost_provisioner login nobypassrls;
  end if;
end $$;

grant create on database :DBNAME to outpost_migrate;

set role outpost_migrate;

create schema if not exists platform authorization outpost_migrate;
create schema if not exists catalog  authorization outpost_migrate;
create schema if not exists outpost  authorization outpost_migrate;

-- ---------------------------------------------------------------------------
-- 1. Tenant context helpers
-- ---------------------------------------------------------------------------
-- The middleware runs, inside the request transaction:
--   SET LOCAL app.tenant_id      = '<acting tenant uuid>';
--   SET LOCAL app.home_tenant_id = '<actor home tenant uuid>';
--   SET LOCAL app.user_id        = '<actor user uuid>';
-- Unset means NULL, and NULL never equals a tenant_id, so an unscoped session sees nothing
-- and can insert nothing. Fail closed.

create or replace function outpost.tenant() returns uuid
  language sql stable parallel safe
  as $$ select nullif(current_setting('app.tenant_id', true), '')::uuid $$;

create or replace function outpost.home_tenant() returns uuid
  language sql stable parallel safe
  as $$ select nullif(current_setting('app.home_tenant_id', true), '')::uuid $$;

create or replace function outpost.actor() returns uuid
  language sql stable parallel safe
  as $$ select nullif(current_setting('app.user_id', true), '')::uuid $$;

-- Standard protection for a tenant table: enable + force RLS, one isolation policy.
create or replace procedure outpost.protect(tbl regclass)
  language plpgsql as $$
begin
  execute format('alter table %s enable row level security', tbl);
  execute format('alter table %s force row level security', tbl);
  execute format('drop policy if exists tenant_isolation on %s', tbl);
  execute format(
    'create policy tenant_isolation on %s using (tenant_id = outpost.tenant()) with check (tenant_id = outpost.tenant())',
    tbl);
end $$;

create or replace function outpost.touch() returns trigger
  language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- ---------------------------------------------------------------------------
-- 2. platform.*  (no tenant data)
-- ---------------------------------------------------------------------------
create table if not exists platform.tenants (
  id             uuid primary key default gen_random_uuid(),
  kind           text not null check (kind in ('customer', 'firm')),
  name           text not null,
  slug           text not null unique,
  status         text not null default 'active' check (status in ('provisioning', 'active', 'suspended', 'offboarding', 'offboarded')),
  kms_key_arn    text,
  es_alias       text unique,
  redis_prefix   text unique,
  created_at     timestamptz not null default now(),
  offboarded_at  timestamptz,
  unique (id, kind)                                   -- lets engagements pin the kind by FK
);

create table if not exists platform.users (
  id              uuid primary key default gen_random_uuid(),
  home_tenant_id  uuid not null references platform.tenants (id),
  idp_subject     text not null unique,
  email           text not null,
  display_name    text not null,
  mfa_kind        text not null default 'none' check (mfa_kind in ('none', 'totp', 'webauthn')),
  status          text not null default 'active' check (status in ('invited', 'active', 'disabled')),
  created_at      timestamptz not null default now(),
  unique (home_tenant_id, email)
);

-- One row per issued access token family. Revocation is checked on every request.
create table if not exists platform.sessions (
  sid               uuid primary key,
  user_id           uuid not null references platform.users (id),
  home_tenant_id    uuid not null references platform.tenants (id),
  acting_tenant_id  uuid not null references platform.tenants (id),
  engagement_id     uuid,                              -- set when acting_tenant != home_tenant
  role              text not null,
  issued_at         timestamptz not null default now(),
  expires_at        timestamptz not null,
  revoked_at        timestamptz,
  revoked_reason    text,
  ip                inet,
  user_agent        text
);
create index if not exists sessions_user_idx on platform.sessions (user_id, issued_at desc);

create table if not exists platform.engagements (
  id                  uuid primary key default gen_random_uuid(),
  firm_tenant_id      uuid not null,
  firm_kind           text not null default 'firm' check (firm_kind = 'firm'),
  customer_tenant_id  uuid not null,
  customer_kind       text not null default 'customer' check (customer_kind = 'customer'),
  starts_at           timestamptz not null default now(),
  ends_at             timestamptz not null,
  status              text not null default 'active' check (status in ('draft', 'active', 'ended', 'terminated')),
  created_by          uuid not null references platform.users (id),
  created_at          timestamptz not null default now(),
  check (ends_at > starts_at),
  foreign key (firm_tenant_id, firm_kind)         references platform.tenants (id, kind),
  foreign key (customer_tenant_id, customer_kind) references platform.tenants (id, kind)
);
create index if not exists engagements_customer_idx on platform.engagements (customer_tenant_id, status);
create index if not exists engagements_firm_idx     on platform.engagements (firm_tenant_id, status);

-- A consultant reaches a customer tenant only through an unrevoked row here, inside the
-- engagement window. The customer can revoke; the firm cannot override that.
create table if not exists platform.engagement_assignments (
  id             uuid primary key default gen_random_uuid(),
  engagement_id  uuid not null references platform.engagements (id),
  user_id        uuid not null references platform.users (id),
  role           text not null check (role in ('lead', 'analyst')),
  granted_by     uuid not null references platform.users (id),
  granted_at     timestamptz not null default now(),
  revoked_by     uuid references platform.users (id),
  revoked_at     timestamptz,
  revoked_side   text check (revoked_side in ('firm', 'customer')),
  unique (engagement_id, user_id)
);

alter table platform.sessions
  add constraint sessions_engagement_fk foreign key (engagement_id) references platform.engagements (id);

-- Counts only. Written by each tenant's own jobs; read by the Command Deck fleet view.
-- This is the only thing a consultant sees across clients without switching context.
create table if not exists platform.engagement_summaries (
  engagement_id         uuid primary key references platform.engagements (id),
  missions_due          integer not null default 0,
  approvals_waiting     integer not null default 0,
  sorties_failed_7d     integer not null default 0,
  findings_open         integer not null default 0,
  findings_critical     integer not null default 0,
  connectors_unhealthy  integer not null default 0,
  posture_band          text,
  as_of                 timestamptz not null default now()
);

create table if not exists platform.break_glass_grants (
  id               uuid primary key default gen_random_uuid(),
  tenant_id        uuid not null references platform.tenants (id),
  admin_user_id    uuid not null references platform.users (id),
  approver_user_id uuid not null references platform.users (id),
  reason           text not null,
  starts_at        timestamptz not null default now(),
  ends_at          timestamptz not null,
  revoked_at       timestamptz,
  check (admin_user_id <> approver_user_id),
  check (ends_at <= starts_at + interval '4 hours')
);

-- ---------------------------------------------------------------------------
-- 3. catalog.*  (shared reference data, read-only to the app)
-- ---------------------------------------------------------------------------
create table if not exists catalog.connector_types (
  id               text primary key,                  -- 'entra-id', 'aws'
  family           text not null,                     -- 'identity', 'cloud', 'code', ...
  display_name     text not null,
  auth_kind        text not null check (auth_kind in ('oauth', 'aws-role', 'gcp-wif', 'azure-federated', 'api-key')),
  capabilities     jsonb not null,                    -- [{"id":"read:identity","permissions":[...]}, ...]
  trust_template   jsonb,                             -- what the customer applies in their console
  docs_url         text,
  version          integer not null default 1
);

create table if not exists catalog.missions (
  id                     text primary key,            -- 'identity-baseline', 'cloud-cis-foundations-aws'
  domain                 text not null,
  title                  text not null,
  summary                text not null,
  tool                   text not null,               -- which Reasoning Engine tool runs it
  required_capabilities  text[] not null,             -- all must be present on healthy connectors
  seed_dataset           text,                        -- e.g. 'cloud-baseline.json'
  questionnaire          jsonb,                       -- questions without evidence hooks
  checks                 jsonb not null,              -- [{"id","title","severity","refs","evidence":{...}}]
  version                integer not null default 1
);

create table if not exists catalog.agents (
  id          text primary key,
  name        text not null,
  model_tier  text not null check (model_tier in ('opus', 'sonnet', 'haiku')),
  tools       text[] not null,                        -- MCP tool ids this agent may call
  risk_tier   text not null check (risk_tier in ('low', 'medium', 'high')),  -- from the AI risk tiering tool
  threat_model_ref text,                              -- link to the AI threat model artifact
  version     integer not null default 1
);

create table if not exists catalog.mcp_servers (
  id             text primary key,
  name           text not null,
  origin         text not null check (origin in ('first-party', 'third-party')),
  image_digest   text not null,                       -- pinned; a new digest is a new review
  review_status  text not null check (review_status in ('pending', 'approved', 'rejected', 'revoked')),
  reviewed_by    text,
  reviewed_at    timestamptz,
  tools          jsonb not null                       -- [{"id","params_schema","writes":bool}]
);

create table if not exists catalog.playbooks (
  id                 text primary key,
  domain             text not null,
  title              text not null,
  summary            text not null,
  agent_id           text not null references catalog.agents (id),
  mcp_server_ids     text[] not null,
  blast_radius       text not null check (blast_radius in ('low', 'medium', 'high')),
  reversible         boolean not null,
  mode_ceiling       text not null check (mode_ceiling in ('autopilot', 'clearance', 'beacon')),
  required_capabilities text[] not null,              -- write scopes it needs
  resolves_checks    text[] not null,                 -- catalog.missions checks it can close
  call_schema        jsonb not null,                  -- allowed tool calls + parameter constraints
  verification       jsonb not null,                  -- the check to re-run after execution
  rollback           jsonb,                           -- null when not reversible
  default_cadence    text not null,                   -- cron or 'on-finding'
  version            integer not null default 1,
  check ((reversible and rollback is not null) or (not reversible and mode_ceiling <> 'autopilot'))
);

-- ---------------------------------------------------------------------------
-- 4. outpost.*  (tenant-scoped; every table gets protect())
-- ---------------------------------------------------------------------------
create table if not exists outpost.provider_policies (
  tenant_id     uuid primary key default outpost.tenant() references platform.tenants (id),
  providers     text[] not null default '{bedrock}' check (providers <@ '{bedrock,openai,gemini}'::text[] and cardinality(providers) > 0),
  guardrail_id  text,
  residency     text not null default 'us' check (residency in ('us', 'eu')),
  default_tier  text not null default 'opus' check (default_tier in ('opus', 'sonnet', 'haiku')),
  updated_by    uuid,
  updated_at    timestamptz not null default now()
);

create table if not exists outpost.customer_profiles (
  tenant_id    uuid primary key default outpost.tenant() references platform.tenants (id),
  industry     text,
  headcount    integer,
  regions      text[] not null default '{}',
  data_types   text[] not null default '{}',           -- 'phi', 'pci', 'pii', 'cui', ...
  regulations  text[] not null default '{}',           -- from regulations.json triggers
  clouds       text[] not null default '{}',
  updated_at   timestamptz not null default now()
);

create table if not exists outpost.connectors (
  tenant_id        uuid not null default outpost.tenant() references platform.tenants (id),
  id               uuid not null default gen_random_uuid(),
  type_id          text not null references catalog.connector_types (id),
  display_name     text not null,
  status           text not null default 'requested'
                   check (status in ('requested', 'awaiting_customer', 'connected', 'degraded', 'revoked', 'expired')),
  external_ref     jsonb not null default '{}',        -- {"aws_account_id":...} / {"entra_tenant_id":...}; never secrets
  requested_scopes text[] not null default '{}',
  granted_scopes   text[] not null default '{}',
  capabilities     text[] not null default '{}',       -- derived from granted_scopes at health-check time
  health           jsonb,
  last_checked_at  timestamptz,
  requested_by     uuid,                               -- consultant or customer admin
  completed_by     uuid,                               -- always a customer user
  completed_at     timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  primary key (id),
  unique (tenant_id, id)
);
create index if not exists connectors_tenant_idx on outpost.connectors (tenant_id, status);

create table if not exists outpost.connector_secrets (
  tenant_id           uuid not null default outpost.tenant(),
  id                  uuid primary key default gen_random_uuid(),
  connector_id        uuid not null,
  kind                text not null check (kind in ('oauth-refresh', 'aws-role', 'gcp-wif', 'azure-federated', 'api-key')),
  ciphertext          bytea not null,                  -- KMS envelope: encrypted data key + payload
  kms_key_arn         text not null,
  encryption_context  jsonb not null,                  -- must contain {"tenant_id": <tenant_id>}
  rotated_at          timestamptz not null default now(),
  expires_at          timestamptz,
  foreign key (tenant_id, connector_id) references outpost.connectors (tenant_id, id) on delete cascade,
  check (encryption_context ->> 'tenant_id' = tenant_id::text)
);

create table if not exists outpost.mission_runs (
  tenant_id        uuid not null default outpost.tenant() references platform.tenants (id),
  id               uuid primary key default gen_random_uuid(),
  mission_id       text not null references catalog.missions (id),
  engagement_id    uuid references platform.engagements (id),
  status           text not null default 'scoped'
                   check (status in ('scoped', 'assessing', 'awaiting_answers', 'briefed', 'planned', 'failed', 'cancelled')),
  scope            jsonb not null,                     -- subscriptions, OUs, repos, ... enforced at connector-call time
  connector_ids    uuid[] not null,
  previous_run_id  uuid,
  started_by       uuid,
  started_at       timestamptz,
  finished_at      timestamptz,
  score            numeric(5, 2),
  band             text,
  result           jsonb,                              -- AssessmentResult shape from assessment.ts
  model_route      jsonb,                              -- provider/model actually used, for the record
  created_at       timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, previous_run_id) references outpost.mission_runs (tenant_id, id)
);
create index if not exists mission_runs_tenant_idx on outpost.mission_runs (tenant_id, mission_id, created_at desc);

create table if not exists outpost.mission_answers (
  tenant_id       uuid not null default outpost.tenant(),
  mission_run_id  uuid not null,
  question_id     text not null,
  answer          text not null check (answer in ('yes', 'alt', 'na', 'no')),
  evidence        jsonb,                               -- connector evidence when auto-answered
  answered_by     uuid,                                -- null when auto-answered
  answered_at     timestamptz not null default now(),
  primary key (tenant_id, mission_run_id, question_id),
  foreign key (tenant_id, mission_run_id) references outpost.mission_runs (tenant_id, id) on delete cascade
);

create table if not exists outpost.findings (
  tenant_id            uuid not null default outpost.tenant() references platform.tenants (id),
  id                   uuid primary key default gen_random_uuid(),
  mission_run_id       uuid not null,
  mission_id           text not null references catalog.missions (id),
  check_id             text not null,
  fingerprint          text not null,                  -- stable across runs: check_id + asset set
  title                text not null,
  severity             text not null check (severity in ('critical', 'high', 'medium', 'low', 'info')),
  status               text not null default 'open' check (status in ('open', 'accepted_risk', 'in_remediation', 'resolved', 'reopened')),
  crosswalk_domain     text,                           -- crosswalk.json control id
  framework_refs       jsonb not null default '[]',    -- [{"framework":"csf","ref":"PR.AA-01"}, ...]
  explanation          text,                           -- plain-English, from the framework corpora
  evidence             jsonb not null default '{}',
  first_seen_at        timestamptz not null default now(),
  last_seen_at         timestamptz not null default now(),
  resolved_at          timestamptz,
  resolved_by_sortie   uuid,
  updated_at           timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, fingerprint),
  foreign key (tenant_id, mission_run_id) references outpost.mission_runs (tenant_id, id)
);
create index if not exists findings_open_idx on outpost.findings (tenant_id, status, severity);

create table if not exists outpost.finding_assets (
  tenant_id   uuid not null default outpost.tenant(),
  finding_id  uuid not null,
  asset_kind  text not null,                           -- 'user', 'aws:s3', 'repo', 'host', ...
  asset_ref   text not null,
  primary key (tenant_id, finding_id, asset_kind, asset_ref),
  foreign key (tenant_id, finding_id) references outpost.findings (tenant_id, id) on delete cascade
);

create table if not exists outpost.recommendations (
  tenant_id          uuid not null default outpost.tenant() references platform.tenants (id),
  id                 uuid primary key default gen_random_uuid(),
  mission_run_id     uuid not null,
  playbook_id        text not null references catalog.playbooks (id),
  finding_ids        uuid[] not null,
  suggested_mode     text not null check (suggested_mode in ('autopilot', 'clearance', 'beacon')),
  suggested_cadence  text not null,
  rationale          text not null,
  decision           text not null default 'pending' check (decision in ('pending', 'accepted', 'rejected', 'deferred')),
  decided_by         uuid,
  decided_at         timestamptz,
  created_at         timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, mission_run_id) references outpost.mission_runs (tenant_id, id)
);

-- A playbook switched on for this tenant, with its mode and cadence. Mode may never exceed
-- catalog.playbooks.mode_ceiling; the API enforces it and the sortie workflow re-checks it.
create table if not exists outpost.playbook_enablements (
  tenant_id        uuid not null default outpost.tenant() references platform.tenants (id),
  id               uuid primary key default gen_random_uuid(),
  playbook_id      text not null references catalog.playbooks (id),
  mode             text not null check (mode in ('autopilot', 'clearance', 'beacon')),
  cadence          text not null,                      -- cron expression
  change_window    jsonb,                              -- {"tz":"America/Chicago","days":[...],"start":"22:00","end":"04:00"}
  enabled          boolean not null default false,
  enabled_at       timestamptz,
  disabled_at      timestamptz,
  disabled_by      uuid,
  temporal_schedule_id text,
  consecutive_verified integer not null default 0,     -- autopilot needs 3
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (tenant_id, id),
  unique (tenant_id, playbook_id)
);

-- One execution of a playbook ("sortie"). Mirrors the Temporal workflow; Postgres is the record.
create table if not exists outpost.sorties (
  tenant_id             uuid not null default outpost.tenant() references platform.tenants (id),
  id                    uuid primary key default gen_random_uuid(),
  playbook_id           text not null references catalog.playbooks (id),
  enablement_id         uuid,
  trigger               text not null check (trigger in ('scheduled', 'manual', 'on_finding')),
  mode                  text not null check (mode in ('autopilot', 'clearance', 'beacon')),
  status                text not null default 'planning'
                        check (status in ('planning', 'previewed', 'awaiting_clearance', 'approved', 'executing',
                                          'verifying', 'succeeded', 'verification_failed', 'rolled_back',
                                          'rollback_failed', 'rejected', 'expired', 'cancelled', 'failed')),
  temporal_workflow_id  text unique,
  finding_ids           uuid[] not null default '{}',
  preview               jsonb,                         -- the exact calls it will make
  preview_hash          bytea,                         -- sha256(canonical(preview)); approvals bind to this
  plan_summary          text,                          -- agent's explanation for the approver
  requested_by          uuid,
  run_credentials_expire_at timestamptz,
  started_at            timestamptz,
  executed_at           timestamptz,
  finished_at           timestamptz,
  result                jsonb,
  verification          jsonb,
  killed_at             timestamptz,
  killed_by             uuid,
  created_at            timestamptz not null default now(),
  unique (tenant_id, id),
  foreign key (tenant_id, enablement_id) references outpost.playbook_enablements (tenant_id, id)
);
create index if not exists sorties_tenant_status_idx on outpost.sorties (tenant_id, status, created_at desc);

alter table outpost.findings
  add constraint findings_resolved_by_sortie_fk
  foreign key (tenant_id, resolved_by_sortie) references outpost.sorties (tenant_id, id);

-- Every tool call: previewed, executed, or rolled back. Executed calls must match previewed ones.
create table if not exists outpost.sortie_calls (
  tenant_id    uuid not null default outpost.tenant(),
  sortie_id    uuid not null,
  phase        text not null check (phase in ('preview', 'execute', 'rollback')),
  seq          integer not null,
  mcp_server_id text not null references catalog.mcp_servers (id),
  tool         text not null,
  params       jsonb not null,
  params_hash  bytea not null,
  status       text not null default 'pending' check (status in ('pending', 'ok', 'error', 'rejected', 'skipped')),
  result       jsonb,
  at           timestamptz not null default now(),
  primary key (tenant_id, sortie_id, phase, seq),
  foreign key (tenant_id, sortie_id) references outpost.sorties (tenant_id, id) on delete cascade
);

-- Dual approval: one customer-side and one consultant-side row per subject per preview hash.
create table if not exists outpost.approvals (
  tenant_id        uuid not null default outpost.tenant() references platform.tenants (id),
  id               uuid primary key default gen_random_uuid(),
  subject_kind     text not null check (subject_kind in ('sortie', 'enablement')),
  subject_id       uuid not null,
  subject_hash     bytea not null,                     -- sortie preview_hash, or enablement config hash
  side             text not null check (side in ('customer', 'consultant')),
  approver_user_id uuid not null,
  decision         text not null check (decision in ('approved', 'rejected')),
  comment          text,
  decided_at       timestamptz not null default now(),
  expires_at       timestamptz not null default now() + interval '72 hours',
  consumed_at      timestamptz,                        -- set when the sortie executes; single-use
  unique (tenant_id, subject_kind, subject_id, subject_hash, side)
);

create table if not exists outpost.remediation_plans (
  tenant_id    uuid not null default outpost.tenant() references platform.tenants (id),
  id           uuid primary key default gen_random_uuid(),
  title        text not null,
  start_month  date not null,
  created_by   uuid,
  created_at   timestamptz not null default now(),
  unique (tenant_id, id)
);

create table if not exists outpost.plan_tasks (
  tenant_id          uuid not null default outpost.tenant(),
  id                 uuid primary key default gen_random_uuid(),
  plan_id            uuid not null,
  recommendation_id  uuid,
  title              text not null,
  quarter            smallint not null check (quarter between 1 and 8),
  status             text not null default 'todo' check (status in ('todo', 'doing', 'done', 'skipped')),
  owner_user_id      uuid,
  due_date           date,
  note               text,
  kpis               jsonb not null default '[]',      -- [{"text","status":"met|partial|unmet"}]
  milestones         jsonb not null default '[]',
  hours              numeric(6, 1),
  updated_at         timestamptz not null default now(),
  foreign key (tenant_id, plan_id) references outpost.remediation_plans (tenant_id, id) on delete cascade,
  foreign key (tenant_id, recommendation_id) references outpost.recommendations (tenant_id, id)
);

-- External attack surface: an asset is scanned only after ownership is verified.
create table if not exists outpost.scan_assets (
  tenant_id              uuid not null default outpost.tenant() references platform.tenants (id),
  id                     uuid primary key default gen_random_uuid(),
  kind                   text not null check (kind in ('domain', 'host', 'cidr')),
  value                  text not null,
  source                 text not null check (source in ('manual', 'aws-inventory', 'dns-enum', 'ct-log')),
  proposed_by            uuid,
  verification_method    text check (verification_method in ('dns-txt', 'well-known', 'cloud-inventory')),
  verified_at            timestamptz,
  verified_by            uuid,                         -- a customer user, or null for cloud-inventory
  active_probing_allowed boolean not null default false,
  rate_limit_rps         numeric(6, 2) not null default 2,
  retired_at             timestamptz,
  unique (tenant_id, id),
  unique (tenant_id, kind, value),
  check (not active_probing_allowed or verified_at is not null)
);

create table if not exists outpost.scan_observations (
  tenant_id     uuid not null default outpost.tenant(),
  id            uuid primary key default gen_random_uuid(),
  asset_id      uuid not null,
  observed_at   timestamptz not null default now(),
  kind          text not null check (kind in ('dns', 'cert', 'port', 'http', 'tls')),
  fingerprint   text not null,
  data          jsonb not null,
  gone_at       timestamptz,                           -- set when a later scan no longer sees it
  foreign key (tenant_id, asset_id) references outpost.scan_assets (tenant_id, id) on delete cascade
);
create index if not exists scan_observations_asset_idx on outpost.scan_observations (tenant_id, asset_id, fingerprint);

create table if not exists outpost.notifications (
  tenant_id   uuid not null default outpost.tenant() references platform.tenants (id),
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null,
  kind        text not null,                            -- 'beacon', 'clearance_requested', 'sortie_failed', ...
  subject     text not null,
  payload     jsonb not null default '{}',
  channel     text not null default 'in_app' check (channel in ('in_app', 'email', 'slack', 'teams')),
  sent_at     timestamptz,
  read_at     timestamptz,
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- 5. Flight recorder: append-only, hash-chained per tenant
-- ---------------------------------------------------------------------------
-- The app may INSERT, and only INSERT. A consultant acting in a customer tenant writes an event
-- to the customer's chain AND to their firm's chain, so the insert policy allows both the acting
-- and the home tenant. Reads stay acting-tenant only.
create table if not exists outpost.audit_events (
  tenant_id             uuid not null references platform.tenants (id),
  seq                   bigint not null,
  at                    timestamptz not null default now(),
  actor_user_id         uuid,
  actor_home_tenant_id  uuid,
  engagement_id         uuid,
  action                text not null,                 -- 'session.switch', 'finding.read', 'sortie.approve', ...
  resource_kind         text,
  resource_id           uuid,
  target_tenant_id      uuid,                          -- set on cross-tenant attempts (always denied)
  request_id            text,
  ip                    inet,
  detail                jsonb not null default '{}',
  prev_hash             bytea,
  hash                  bytea not null,
  primary key (tenant_id, seq)
);

-- Serializes per tenant, links to the previous row, computes the hash. SECURITY DEFINER so it can
-- read the previous row of the home tenant's chain while the session is scoped to the acting
-- tenant; audit_events is therefore ENABLED but not FORCED (owner-bypass is what makes the
-- lookup work). check_rls.sql carries this one table as a named exception.
create or replace function outpost.audit_chain() returns trigger
  language plpgsql security definer set search_path = outpost, pg_temp as $$
declare
  last_seq  bigint;
  last_hash bytea;
begin
  perform pg_advisory_xact_lock(hashtext(new.tenant_id::text));
  select seq, hash into last_seq, last_hash
    from outpost.audit_events where tenant_id = new.tenant_id order by seq desc limit 1;
  new.seq       := coalesce(last_seq, 0) + 1;
  new.at        := coalesce(new.at, now());
  new.prev_hash := last_hash;
  new.hash      := sha256(coalesce(last_hash, '\x'::bytea) || convert_to(
                     concat_ws('|', new.tenant_id, new.seq, new.at, new.actor_user_id, new.actor_home_tenant_id,
                               new.engagement_id, new.action, new.resource_kind, new.resource_id,
                               new.target_tenant_id, new.request_id, new.detail::text), 'UTF8'));
  return new;
end $$;

drop trigger if exists audit_chain on outpost.audit_events;
create trigger audit_chain before insert on outpost.audit_events
  for each row execute function outpost.audit_chain();

-- Nightly: verify a tenant's chain end to end. Returns the first broken seq, or null.
create or replace function outpost.audit_verify(p_tenant uuid) returns bigint
  language plpgsql security definer set search_path = outpost, pg_temp as $$
declare
  r         record;
  expected  bytea;
  prev      bytea := null;
begin
  for r in select * from outpost.audit_events where tenant_id = p_tenant order by seq loop
    expected := sha256(coalesce(prev, '\x'::bytea) || convert_to(
                  concat_ws('|', r.tenant_id, r.seq, r.at, r.actor_user_id, r.actor_home_tenant_id,
                            r.engagement_id, r.action, r.resource_kind, r.resource_id,
                            r.target_tenant_id, r.request_id, r.detail::text), 'UTF8'));
    if r.hash <> expected or r.prev_hash is distinct from prev then
      return r.seq;
    end if;
    prev := r.hash;
  end loop;
  return null;
end $$;

alter table outpost.audit_events enable row level security;
drop policy if exists audit_read on outpost.audit_events;
create policy audit_read on outpost.audit_events for select
  using (tenant_id = outpost.tenant());
drop policy if exists audit_insert on outpost.audit_events;
create policy audit_insert on outpost.audit_events for insert
  with check (tenant_id = outpost.tenant() or tenant_id = outpost.home_tenant());

-- ---------------------------------------------------------------------------
-- 6. Apply RLS to every tenant table, and updated_at triggers
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  for t in
    select format('%I.%I', schemaname, tablename) from pg_tables
     where schemaname = 'outpost' and tablename <> 'audit_events'
  loop
    call outpost.protect(t::regclass);
  end loop;
end $$;

do $$
declare t text;
begin
  for t in
    select format('%I.%I', c.table_schema, c.table_name) from information_schema.columns c
     where c.table_schema = 'outpost' and c.column_name = 'updated_at'
  loop
    execute format('drop trigger if exists touch on %s', t);
    execute format('create trigger touch before update on %s for each row execute function outpost.touch()', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 7. Grants
-- ---------------------------------------------------------------------------
grant usage on schema platform, catalog, outpost to outpost_app, outpost_provisioner;

-- Request path
grant select on all tables in schema catalog to outpost_app;
grant select on platform.tenants, platform.users, platform.engagements, platform.engagement_assignments,
                platform.engagement_summaries, platform.break_glass_grants to outpost_app;
grant select, insert, update on platform.sessions to outpost_app;
grant update (mfa_kind, display_name, status) on platform.users to outpost_app;
grant insert, update on platform.engagement_summaries to outpost_app;
grant select, insert, update, delete on all tables in schema outpost to outpost_app;
revoke update, delete, truncate on outpost.audit_events from outpost_app;
grant execute on function outpost.audit_verify(uuid) to outpost_app;

-- Provisioning job (tenant create / offboard, engagement admin)
grant select, insert, update on platform.tenants, platform.users, platform.engagements,
                               platform.engagement_assignments, platform.break_glass_grants to outpost_provisioner;
grant select, insert, update, delete on all tables in schema outpost to outpost_provisioner;
revoke update, delete, truncate on outpost.audit_events from outpost_provisioner;
grant select, insert, update, delete on all tables in schema catalog to outpost_provisioner;

alter default privileges for role outpost_migrate in schema outpost grant select, insert, update, delete on tables to outpost_app;
alter default privileges for role outpost_migrate in schema catalog grant select on tables to outpost_app;

reset role;
